// Generated by scripts/build-move-effects.ts — do not edit (plan 234).

/** Where each effect strip sits in `assets/effects/move-effects.png`, in sheet pixels. */
export interface MoveEffectStrip {
  x: number;
  y: number;
  frameWidth: number;
  frameHeight: number;
  frames: number;
  /** One row per direction (PMD Dir8 order: Down, DownLeft, Left, UpLeft, Up, UpRight, Right, DownRight). */
  rows: number;
}

export const MOVE_EFFECT_SHEET_URL = "assets/effects/move-effects.png";
export const MOVE_EFFECT_SHEET_WIDTH = 2048;
export const MOVE_EFFECT_SHEET_HEIGHT = 1022;

export const MOVE_EFFECT_STRIPS = {
  "beam-body": { x: 1270, y: 1006, frameWidth: 32, frameHeight: 1, frames: 14, rows: 1 },
  "beam-head": { x: 0, y: 940, frameWidth: 32, frameHeight: 32, frames: 14, rows: 1 },
  "blocked-ring": { x: 0, y: 973, frameWidth: 32, frameHeight: 32, frames: 9, rows: 1 },
  cry: { x: 0, y: 0, frameWidth: 88, frameHeight: 88, frames: 6, rows: 8 },
  gaze: { x: 289, y: 802, frameWidth: 64, frameHeight: 64, frames: 11, rows: 1 },
  gust: { x: 1091, y: 875, frameWidth: 48, frameHeight: 48, frames: 12, rows: 1 },
  "heal-sparkle": { x: 1221, y: 1006, frameWidth: 8, frameHeight: 8, frames: 6, rows: 1 },
  hit: { x: 1507, y: 802, frameWidth: 64, frameHeight: 64, frames: 4, rows: 1 },
  "hit-strong": { x: 0, y: 875, frameWidth: 64, frameHeight: 64, frames: 6, rows: 1 },
  "mark-bite": { x: 818, y: 0, frameWidth: 56, frameHeight: 56, frames: 4, rows: 8 },
  "mark-chop": { x: 1508, y: 973, frameWidth: 16, frameHeight: 16, frames: 1, rows: 1 },
  "mark-claw": { x: 1668, y: 875, frameWidth: 40, frameHeight: 40, frames: 7, rows: 1 },
  "mark-jab": { x: 1043, y: 0, frameWidth: 48, frameHeight: 48, frames: 4, rows: 8 },
  "mark-kick": { x: 1491, y: 973, frameWidth: 16, frameHeight: 16, frames: 1, rows: 1 },
  "mark-punch": { x: 1474, y: 973, frameWidth: 16, frameHeight: 16, frames: 1, rows: 1 },
  "mark-slash": { x: 449, y: 940, frameWidth: 32, frameHeight: 32, frames: 4, rows: 1 },
  notes: { x: 0, y: 1006, frameWidth: 16, frameHeight: 16, frames: 44, rows: 1 },
  orb: { x: 1153, y: 705, frameWidth: 80, frameHeight: 80, frames: 11, rows: 1 },
  "projectile-dragon": { x: 740, y: 973, frameWidth: 32, frameHeight: 32, frames: 4, rows: 1 },
  "projectile-fire": { x: 1183, y: 973, frameWidth: 24, frameHeight: 24, frames: 9, rows: 1 },
  "projectile-ghost": { x: 1400, y: 973, frameWidth: 24, frameHeight: 24, frames: 2, rows: 1 },
  "projectile-grass": { x: 289, y: 973, frameWidth: 32, frameHeight: 32, frames: 8, rows: 1 },
  "projectile-ground": { x: 579, y: 973, frameWidth: 32, frameHeight: 32, frames: 5, rows: 1 },
  "projectile-ice": { x: 546, y: 973, frameWidth: 32, frameHeight: 32, frames: 1, rows: 1 },
  "projectile-rock": { x: 980, y: 1006, frameWidth: 16, frameHeight: 16, frames: 15, rows: 1 },
  "projectile-steel": { x: 1449, y: 973, frameWidth: 24, frameHeight: 24, frames: 1, rows: 1 },
  puff: { x: 578, y: 940, frameWidth: 32, frameHeight: 32, frames: 7, rows: 1 },
  ring: { x: 385, y: 875, frameWidth: 64, frameHeight: 64, frames: 8, rows: 1 },
  screen: { x: 994, y: 802, frameWidth: 64, frameHeight: 64, frames: 8, rows: 1 },
  shield: { x: 898, y: 875, frameWidth: 64, frameHeight: 64, frames: 3, rows: 1 },
  smoke: { x: 803, y: 940, frameWidth: 32, frameHeight: 32, frames: 12, rows: 1 },
  sparkle: { x: 1606, y: 940, frameWidth: 32, frameHeight: 32, frames: 5, rows: 1 },
  "stat-line": { x: 1188, y: 940, frameWidth: 32, frameHeight: 32, frames: 7, rows: 1 },
  "stat-ring": { x: 1413, y: 940, frameWidth: 32, frameHeight: 32, frames: 6, rows: 1 },
  "status-asleep": { x: 869, y: 973, frameWidth: 24, frameHeight: 24, frames: 3, rows: 1 },
  "status-burned": { x: 0, y: 705, frameWidth: 96, frameHeight: 96, frames: 12, rows: 1 },
  "status-confused": { x: 942, y: 973, frameWidth: 24, frameHeight: 24, frames: 10, rows: 1 },
  "status-frozen": { x: 834, y: 1006, frameWidth: 16, frameHeight: 16, frames: 3, rows: 1 },
  "status-infatuated": { x: 883, y: 1006, frameWidth: 16, frameHeight: 16, frames: 6, rows: 1 },
  "status-paralyzed": { x: 0, y: 802, frameWidth: 72, frameHeight: 72, frames: 4, rows: 1 },
  "status-poisoned": { x: 705, y: 1006, frameWidth: 16, frameHeight: 16, frames: 8, rows: 1 },
  wave: { x: 1236, y: 0, frameWidth: 32, frameHeight: 32, frames: 11, rows: 5 },
  "wide-slash": { x: 529, y: 0, frameWidth: 72, frameHeight: 72, frames: 4, rows: 8 },
} as const satisfies Record<string, MoveEffectStrip>;

export type MoveEffectStripKey = keyof typeof MOVE_EFFECT_STRIPS;
