export const BattleEventType = {
  TurnStarted: "turn_started",
  TurnEnded: "turn_ended",
  MoveStarted: "move_started",
  PokemonMoved: "pokemon_moved",
  PokemonDashed: "pokemon_dashed",
  DamageDealt: "damage_dealt",
  StatusApplied: "status_applied",
  StatusRemoved: "status_removed",
  StatChanged: "stat_changed",
  PokemonKo: "pokemon_ko",
  PokemonEliminated: "pokemon_eliminated",
  PokemonRevived: "pokemon_revived",
  MoveMissed: "move_missed",
  DefenseActivated: "defense_activated",
  DefenseCleared: "defense_cleared",
  DefenseTriggered: "defense_triggered",
  BattleEnded: "battle_ended",
  ConfusionTriggered: "confusion_triggered",
  ConfusionRedirected: "confusion_redirected",
  ConfusionResisted: "confusion_resisted",
  ConfusionFailed: "confusion_failed",
  KnockbackApplied: "knockback_applied",
  KnockbackBlocked: "knockback_blocked",
  MultiHitComplete: "multi_hit_complete",
  RechargeStarted: "recharge_started",
  RechargeEnded: "recharge_ended",
  FallDamageDealt: "fall_damage_dealt",
  WallImpactDealt: "wall_impact_dealt",
  TerrainDamageDealt: "terrain_damage_dealt",
  TerrainStatusApplied: "terrain_status_applied",
  IceSlideApplied: "ice_slide_applied",
  IceSlideCollision: "ice_slide_collision",
  LethalTerrainKo: "lethal_terrain_ko",
  MoveCancelled: "move_cancelled",
} as const;

export type BattleEventType = (typeof BattleEventType)[keyof typeof BattleEventType];
