export const HeldItemId = {
  Leftovers: "leftovers",
  LifeOrb: "life-orb",
  ChoiceBand: "choice-band",
  ChoiceScarf: "choice-scarf",
  FocusSash: "focus-sash",
  ExpertBelt: "expert-belt",
  RockyHelmet: "rocky-helmet",
  WeaknessPolicy: "weakness-policy",
  ScopeLens: "scope-lens",
  SitrusBerry: "sitrus-berry",
  HeavyDutyBoots: "heavy-duty-boots",
  LightBall: "light-ball",
  ChoiceSpecs: "choice-specs",
  Eviolite: "eviolite",
  BlackSludge: "black-sludge",
  Leek: "stick",
  ThickClub: "thick-club",
  WhiteHerb: "white-herb",
  FlameOrb: "flame-orb",
  SalacBerry: "salac-berry",
  NormalGem: "normal-gem",
  HeatRock: "heat-rock",
} as const;

export type HeldItemId = (typeof HeldItemId)[keyof typeof HeldItemId];
