export const HeldItemId = {
  Leftovers: "leftovers",
  LifeOrb: "life-orb",
  ChoiceBand: "choice-band",
  ChoiceScarf: "choice-scarf",
  FocusSash: "focus-sash",
  ExpertBelt: "expert-belt",
  RockyHelmet: "rocky-helmet",
  WeaknessPolicy: "weakness-policy",
  ScopeLens: "scope-lens",
  SitrusBerry: "sitrus-berry",
  HeavyDutyBoots: "heavy-duty-boots",
  LightBall: "light-ball",
  ChoiceSpecs: "choice-specs",
  Eviolite: "eviolite",
  BlackSludge: "black-sludge",
  Leek: "stick",
  ThickClub: "thick-club",
  WhiteHerb: "white-herb",
  FlameOrb: "flame-orb",
  SalacBerry: "salac-berry",
  NormalGem: "normal-gem",
  HeatRock: "heat-rock",
  LightClay: "light-clay",
  TerrainExtender: "terrain-extender",
  SilkScarf: "silk-scarf",
  Charcoal: "charcoal",
  MysticWater: "mystic-water",
  MiracleSeed: "miracle-seed",
  Magnet: "magnet",
  NeverMeltIce: "never-melt-ice",
  BlackBelt: "black-belt",
  PoisonBarb: "poison-barb",
  SoftSand: "soft-sand",
  SharpBeak: "sharp-beak",
  TwistedSpoon: "twisted-spoon",
  SilverPowder: "silver-powder",
  HardStone: "hard-stone",
  SpellTag: "spell-tag",
  DragonFang: "dragon-fang",
  BlackGlasses: "black-glasses",
  MetalCoat: "metal-coat",
  FairyFeather: "fairy-feather",
} as const;

export type HeldItemId = (typeof HeldItemId)[keyof typeof HeldItemId];
