export const Nature = {
  Hardy: "hardy",
  Lonely: "lonely",
  Brave: "brave",
  Adamant: "adamant",
  Naughty: "naughty",
  Bold: "bold",
  Docile: "docile",
  Relaxed: "relaxed",
  Impish: "impish",
  Lax: "lax",
  Timid: "timid",
  Hasty: "hasty",
  Serious: "serious",
  Jolly: "jolly",
  Naive: "naive",
  Modest: "modest",
  Mild: "mild",
  Quiet: "quiet",
  Bashful: "bashful",
  Rash: "rash",
  Calm: "calm",
  Gentle: "gentle",
  Sassy: "sassy",
  Careful: "careful",
  Quirky: "quirky",
} as const;

export type Nature = (typeof Nature)[keyof typeof Nature];
